### ISSUE TITLE
Pixel Overflow

### ISSUE THREAD

**Issue by aayussraut** [HamroRepo/covid-update#1]
There is a pixel overflow  in searchable_dropdown by 12 pixel

![Screenshot_1597835221](https://user-images.githubusercontent.com/48161121/90716523-e156f680-e2cc-11ea-9f8d-4d4397cfd286.png)

**Comment by rabin245** [comment]
man fuck you 
kei na kei hola vaneko ta mug

**Comment by aayussraut** [comment]
@rabin245  sorry for the disturbance . The problem has been fixed.
